title: "Wishful Shrinking"
theme: jekyll-theme-hacker

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-W10-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
